# Generated by Django 3.2.13 on 2022-06-24 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='games',
            new_name='store',
        ),
    ]
